source 'https://github.com/CocoaPods/Specs.git'
use_modular_headers!
platform :ios, '10.0'

target 'XKProjectModule_Example' do
  pod 'XKProjectModule', :path => '../'

  target 'XKProjectModule_Tests' do
    inherit! :search_paths
  end
  
end
